# -- Site Configuration --
baseURL = "https://notesbynisha.com/"
theme = "congo"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
